"""empty message

Revision ID: 08a871106335
Revises: 9d90c179f5b6
Create Date: 2025-03-29 21:38:08.634847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a871106335'
down_revision = '9d90c179f5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('task_user_id_key', ['user_id'])

    # ### end Alembic commands ###
